# 每天6:30执行
# UTC 时间，北京时间需要 UTC+8
name: Start

on:
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * *'

jobs:
  TiebaSignIn:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # 更新到 v3 版本
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3  # 更新到 v3 版本
      with:
        java-version: 1.8
        distribution: 'temurin'  # 指定 JDK 发行版，temurin 是一个不错的选择
    - name: Cache local Maven repository
      uses: actions/cache@v4  # 更新到 v4 版本
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      env:
        BDUSS: ${{ secrets.BDUSS }}
        SCKEY: ${{ secrets.SCKEY }}
      run: |
        mvn compile exec:java -Dexec.mainClass="top.srcrs.Run" -Dexec.args="${BDUSS} ${SCKEY}"
